### ISSUE TITLE
Bug: No Retry for SSL Error

### ISSUE THREAD

**Issue by lukas-gitl** [shazow/urllib3#1112]
That following code should fire off a `MaxRetryError`, but instead doen't retry and throws an `SSLError`.

**Test case:**
_server.py_
```python
import time
import socket

s = socket.socket()
s.bind(('', 4433))
s.listen(10)

while True:
    news, _ = s.accept()
    time.sleep(0.5)
    news.close()
```
_client.py_
```python
import urllib3
http = urllib3.PoolManager()
http.request('GET', 'https://localhost:4433/', retries=5)
```

<sup>*Disclaimer:* Test case was created by [**Lukasa**](https://github.com/kennethreitz/requests/issues/3845#issuecomment-278273421)</sup>

**Comment by SethMichaelLarson** [comment]
Doesn't look like you're setting up HTTPS on your server. It's just a regular non-SSL socket.

**Comment by Lukasa** [comment]
Ok, so my analysis of this bug is just that we do not retry on `SSLError`, and we probably should. The code block in `ConnectionPool.urlopen` is the one that makes this call, and I think it's just not right. I'm inclined to say that the blocks for `BaseSSLError`, `CertificateError`, and `SSLError` should all be rolled down into the block below.

Thoughts? This is something that would be good for one of the regular contributors to pick up if they want to. =)

**Comment by piquadrat** [comment]
I'm currently trying to implement this as proposed by @Lukasa, basically like this:

    diff --git a/urllib3/connectionpool.py b/urllib3/connectionpool.py
    index b4f1166..031df4c 100644
    --- a/urllib3/connectionpool.py
    +++ b/urllib3/connectionpool.py
    @@ -622,26 +622,16 @@ class HTTPConnectionPool(ConnectionPool, RequestMethods):
                 # Timed out by queue.
                 raise EmptyPoolError(self, "No pool connections are available.")

    -        except (BaseSSLError, CertificateError) as e:
    -            # Close the connection. If a connection is reused on which there
    -            # was a Certificate error, the next request will certainly raise
    -            # another Certificate error.
    -            clean_exit = False
    -            raise SSLError(e)
    -
    -        except SSLError:
    -            # Treat SSLError separately from BaseSSLError to preserve
    -            # traceback.
    -            clean_exit = False
    -            raise
    -
    -        except (TimeoutError, HTTPException, SocketError, ProtocolError) as e:
    +        except (TimeoutError, HTTPException, SocketError, ProtocolError,
    +                BaseSSLError, SSLError, CertificateError) as e:
                 # Discard the connection for these exceptions. It will be
    -            # be replaced during the next _get_conn() call.
    +            # replaced during the next _get_conn() call.
                 clean_exit = False

                 if isinstance(e, (SocketError, NewConnectionError)) and self.proxy:
                     e = ProxyError('Cannot connect to proxy.', e)
    +            elif isinstance(e, (BaseSSLError, CertificateError)):
    +                e = SSLError(e)
                 elif isinstance(e, (SocketError, HTTPException)):
                     e = ProtocolError('Connection aborted.', e)

This introduces a whole bunch of test failures, most of which are because they expect an `SSLError` but are now receiving a `MaxRetryError`. That's easy enough to fix, but it opens up another question: doesn't this break users of the library that specifically want to handle `SSLError` exceptions?

**Comment by Lukasa** [comment]
Yup, but that's ok: urllib3 does not have backward-compatibility guarantees on minor releases, so I'm not too fussed about it. :grin:

**Comment by piquadrat** [comment]
Sweet! I'll open a PR later today then!
