### ISSUE TITLE
Cannot verify website with valid certificate

### ISSUE THREAD

**Issue by kissgyorgy** [shazow/urllib3#1135]
I cannot verify the https://anteus.hu website certificate (https://tls-observatory.services.mozilla.com/static/certsplainer.html?id=9486863) with urllib3 in any way. The Exception is always:
`SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749)`
Every other method says it's valid (Google Chrome, CURL, [oscrypto.tls.TLSSocket](https://github.com/wbond/oscrypto), Mozilla Observatory).

I tried with urllib3 1.19.1 and 1.20, certifi 2016.9.26 and 2017.1.23.
with `certifi`:
```python
import urllib3
import certifi
http = urllib3.PoolManager(cert_reqs='CERT_REQUIRED', ca_certs=certifi.where())
res = http.request('GET', 'https://anteus.hu', redirect=True)
```

without `certifi`:
```python
import urllib3
http = urllib3.PoolManager(cert_reqs='CERT_REQUIRED')
res = http.request('GET', 'https://anteus.hu', redirect=True)
```
a combination of the versions mentioned above, and different timeout, pool_size, etc parameters. The result is always the same. Other sites checked fine (https://twitter.com, https://facebook.com, etc) Previously I made the request with HEAD method, and the server didn't answered to that, but GET is fine with everything else.

My Python version is: Python 3.6.0 (default, Dec 23 2016, 18:35:29)
OS: OS X 10.11.6
`import ssl; ssl.OPENSSL_VERSION`: OpenSSL 1.0.2k  26 Jan 2017

What is happening?

**Comment by Lukasa** [comment]
The server is sending an incomplete cert chain, [as you can see here](https://www.ssllabs.com/ssltest/analyze.html?d=anteus.hu&hideResults=on). The other methods you tested all avoid using OpenSSL to validate the certificates, which means they use AIA-chasing and other techniques to locate intermediate certificates. OpenSSL doesn't do that, so urllib3 in its default configuration doesn't do it either.

Strictly this server is misconfigured, and is just getting away with it because most browsers tolerate it. You can resolve this issue by downloading the appropriate intermediate certificate(s) in PEM format and placing it in a file, then concatenating the file at `certifi.where()` into that same file, and using that new bundle as your trust store.

Alternatively, you can try using the patch in #1122 along with `urllib3.contrib.securetransport.inject_into_urllib3`. That will change to use the macOS default TLS provider, which will retrieve the intermediate certs as needed. Please be aware that the patch there is a beta and not yet merged to urllib3 master.
