### ISSUE TITLE
Should not be error: "urllib3 is using URLFetch on Google App Engine sandbox instead of sockets"

### ISSUE THREAD

**Issue by whipermr5** [shazow/urllib3#1138]
This warning shows up as an error in App Engine logs viewer whenever a new process is started for the application. However, using `URLFetch` is perfectly acceptable - [`urllib3`'s own documentation](https://urllib3.readthedocs.io/en/latest/reference/urllib3.contrib.html) lists it as the first option, and [one of Google's own example applications](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/96ae58c3540959a0d9366fee42366f6edb142b8a/appengine/standard/firebase/firenotes/backend/main.py#L25) uses it via a monkey patch. I'm not sure why this should be logged as an error? An info-level log would be much friendlier.

Relevant code: [here](https://github.com/shazow/urllib3/blob/b6204d57bcdfc6ff048f1c21647ef324c8a4f39e/urllib3/contrib/appengine.py#L111)

**Comment by Lukasa** [comment]
Thanks for this report!

Firstly, let's note that it's not logged at error level: it's raised as a warning. Warnings are generally appropriate things to fire off when you're using a behaviour that may be subtly different from what you're expecting.

In this case, there are some behaviours that urllib3 cannot control when using URLFetch. It's probably fine, but not necessarily, and because it's a behaviour that may not necessarily be visible to the end user of the application (e.g. because of multiple layers of wrapping around urllib3), firing a warning is a useful debugging signal that will help alert users to what's going on.

Because this is a warning, you can silence it by running `warnings.simplefilter("ignore", urllib3.contrib.appengine.AppEnginePlatformWarning)`, which will prevent it from ever being issued.
