### ISSUE TITLE
Import InsecureRequestWarning problem

### ISSUE THREAD

**Issue by tangb** [shazow/urllib3#1156]
Hi

I'm using gTTS package for sometime now and I got an exception after installing fresh latest raspian release.
Here the exception:
```
  File "/usr/local/lib/python2.7/dist-packages/gtts/__init__.py", line 2, in <module>
    from .tts import gTTS
  File "/usr/local/lib/python2.7/dist-packages/gevent/builtins.py", line 93, in __import__
    result = _import(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/gtts/tts.py", line 4, in <module>
    from requests.packages.urllib3.exceptions import InsecureRequestWarning
```

It works well with urllib1.3 but since 1.9.1 (maybe before) it is broken.

Can you confirm me the way to load exceptions have changed ?
Or it is a bug :p ?

Thank you.

Tang

**Comment by Lukasa** [comment]
No, it's [right there](https://github.com/shazow/urllib3/blob/master/urllib3/exceptions.py#L166). Can you show me the *entire* traceback and the error message at the bottom please? I think you have stripped some important context.

**Comment by tangb** [comment]
The full traceback:
```
Traceback (most recent call last):
  File "/usr/bin/test", line 169, in <module>
    module_ = importlib.import_module('test.modules.%s' % module_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/local/lib/python2.7/dist-packages/gevent/builtins.py", line 93, in __import__
    result = _import(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/test/modules/__init__.py", line 3, in <module>
    from test.modules import *
  File "/usr/local/lib/python2.7/dist-packages/gevent/builtins.py", line 93, in __import__
    result = _import(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/test/modules/sounds.py", line 11, in <module>
    from gtts import gTTS
  File "/usr/local/lib/python2.7/dist-packages/gevent/builtins.py", line 93, in __import__
    result = _import(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/gtts/__init__.py", line 2, in <module>
    from .tts import gTTS
  File "/usr/local/lib/python2.7/dist-packages/gevent/builtins.py", line 93, in __import__
    result = _import(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/gtts/tts.py", line 4, in <module>
    from requests.packages.urllib3.exceptions import InsecureRequestWarning
ImportError: cannot import name InsecureRequestWarning
```

**Comment by SethMichaelLarson** [comment]
While you're at it you should include a `pip freeze` as well.

**Comment by tangb** [comment]
I didn't know freeze command :sweat:

Here the result of pip freeze:
Pillow==2.6.1
RPi.GPIO==0.6.3
argparse==1.2.1
astral==1.4
bottle==0.12.13
chardet==2.3.0
colorama==0.3.2
decorator==3.4.0
gTTS==1.2.0
gTTS-token==1.1.1
gevent==1.2.1
greenlet==0.4.12
html5lib==0.999
ndg-httpsclient==0.3.2
numpy==1.8.2
passlib==1.7.1
psutil==5.2.2
pyOpenSSL==0.13.1
pyasn1==0.1.7
pygame==1.9.2a0
pyraspiot==0.0.6
python-apt==0.9.3.12
pytz==2017.2
requests==2.4.3
scipy==0.14.0
simplejson==3.6.5
six==1.8.0
spidev==3.0
urllib3==1.21
wheel==0.24.0
wsgiref==0.1.2

**Comment by SethMichaelLarson** [comment]
I replicated your environment as close as I could barring a few dependencies that don't seem to have those versions available on PyPI anymore. (Are you running your own PyPI server, or where are you getting your dependencies?)

After replicating your environment I was not able to reproduce this issue.
Here is what my replicated environment looks like:

appdirs==1.4.3
astral==1.4
bottle==0.12.13
chardet==2.3.0
colorama==0.3.2
decorator==3.4.0
gevent==1.2.1
greenlet==0.4.12
gTTS==1.2.0
gTTS-token==1.1.1
html5lib==0.999
ndg-httpsclient==0.3.2
numpy==1.8.2
packaging==16.8
passlib==1.7.1
Pillow==2.6.1
psutil==5.2.2
pyasn1==0.1.7
pyOpenSSL==0.13.1
pyparsing==2.2.0
pytz==2017.2
requests==2.4.3
RPi.GPIO==0.6.3
scipy==0.14.0
simplejson==3.6.5
six==1.8.0
spidev==3.0
urllib3==1.21

When I run the following command I get no error:
`python -c 'from requests.packages.urllib3.exceptions import InsecureRequestWarning'`

I'll note that you're using an older version of Requests, upgrading urllib3 won't upgrade the version of urllib3 that Requests uses because Requests vendors it's dependencies. Will investigate further.

**Comment by haikuginger** [comment]
It would be good to have a sample of the minimum set of code you can reproduce this with. Some libraries will trample the namespaces of others, so that could be what we're seeing here.

**Comment by tangb** [comment]
@SethMichaelLarson 
Here is the trace of the same code execution:
```
root@raspberrypi:~# python -c 'from requests.packages.urllib3.exceptions import InsecureRequestWarning'
/usr/local/lib/python2.7/dist-packages/urllib3/contrib/socks.py:37: DependencyWarning: SOCKS support in urllib3 requires the installation of optional dependencies: specifically, PySocks.  For more information, see https://urllib3.readthedocs.io/en/latest/contrib.html#socks-proxies
  DependencyWarning
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: cannot import name InsecureRequestWarning
```
I don't run my own PyPi server. But pyraspiot is my own package.
These are the steps to reproduce my environment:
1. - Install raspbian jessie lite (I downloaded this weekend this version 2017-04-10-raspbian-jessie-lite.zip)
2. - aptitude install python-pip, python-dev, python-pygame, python-spidev, python-scipy, python-simplejson
3. - pip install -r requirements.txt
with requirements.txt content:
```
gevent
bottle
RPi.GPIO
passlib
astral
gTTS
psutil
```
Except pyraspiot package you should have the same environement as me.

**Comment by Lukasa** [comment]
So, the relevant hint here is probably that your Requests is in `dist-packages`. That means it was not installed via `pip`, but via `apt-get` (or more likely, was installed when you installed your OS as its a critical component of your OS). The problem here is likely to be that Debian "unbundles" Requests when it does this, which means it no longer uses a vendored copy of urllib3 but instead uses a separate one.

This means it plays *very poorly* with installing urllib3 separately via `pip`. My bet is that this is a problem with that unbundling process. Assuming it is, your `pip` is likely broken too, as it relies on the same process.

If possible can you try creating a `virtualenv`, entering it, and then using `pip` to install your relevant dependencies? That may work better, assuming your `pip` is still functioning.

**Comment by tangb** [comment]
I tested directly on my current env.
I upgraded requests package (pip install requests --upgrade) and you're right, now I have no error with this _"python -c 'from requests.packages..."_ command :smile:

But now pip is broken. It's not a problem I can't create again my env but what is the good way to install clean python environment ?
According to this experience, using raspbian packages it's not a viable solution (it introduces inconsistent library dependencies). So can you confirm me https://pip.pypa.io/en/stable/installing/ is the good approach ?

Thank you very much for your help guys :smiley:

**Comment by Lukasa** [comment]
Using raspbian packages to fix your default environ is the right thing to do. From then on, you should *always* create and use virtual environments in order to use pip. Inside virtual environments you should only ever use pip, outside them you should only ever use apt-get.

**Comment by tangb** [comment]
Ok, it what I usually do, but when I started my project last year (not on raspbian jessie version) the raspian repo bottle version was too old (0.10) and I needed a feature implemented in 0.12.
It seems in jessie bottle 0.12 version is available, so i can make a try.

Thank you.

**Comment by SethMichaelLarson** [comment]
Just as I suspected! Thanks for handling the end of this @Lukasa :)

**Comment by Lukasa** [comment]
Always happy to help. =)
