### ISSUE TITLE
Using app pass as authentication

### ISSUE THREAD

**Issue by tysondogerz** [shazow/urllib3#1311]
How do I authenticate with urllib3?  Trying to access private repo on bitbucket for updater (though this does not work at all) - https://github.com/JMSwag/PyUpdater/blob/master/pyupdater/client/downloader.py

```
from client_config import ClientConfig
import pyupdater.client.downloader
from pyupdater.client import Client
import urllib3
import certifi

# Monkey patch pyupdater to use basic auth
def get_http_pool_monkey(secure=True):

    headers = urllib3.util.make_headers(basic_auth='%s:%s' % ("username","password"))

    if secure is True:
        http = urllib3.PoolManager(cert_reqs=str('CERT_REQUIRED'),
                                   ca_certs=certifi.where())
        http.headers.update(headers)
        return http
    else:
        http = urllib3.PoolManager()
        http.headers.update(headers)
        return http

pyupdater.client.downloader.get_http_pool = get_http_pool_monkey
```

Now that that is done...

Updater...

```
#!/usr/bin/env python3
from __future__ import print_function
import time
import argparse
import os
import signal
import sys
import logging
from selenium import webdriver
import requests
logging.basicConfig(level=logging.DEBUG)

from client_config import ClientConfig
from pyupdater.client import Client, AppUpdate, LibUpdate

def check_for_update():
    client = Client(ClientConfig(), refresh=True)
    app_update = client.update_check(ClientConfig.APP_NAME, ClientConfig.APP_VERSION, channel='stable')

    if app_update is not None:  # is there a new update
        if app_update.download():  # the update download is made here
            if isinstance(app_update, AppUpdate):  # you should freeze it
                app_update.extract_restart()
                return True
            else:
                app_update.extract()
                return True
    return False


def main():
    print('Current version is ', ClientConfig.APP_VERSION)
    if check_for_update():
        print('there\'s a new update :D')
    driver = webdriver.Firefox()
    driver.get('http://stackoverflow.com')

if __name__ == "__main__":
    main()

```
Tried a few workarounds but cannot workout how.

**Comment by haikuginger** [comment]
While we can't necessarily assist with the full stack of operations, I can provide some pointers.

1. Pass your headers into the `PoolManager` constructor to avoid extra code
2. Manually construct an Authorization header yourself and pass it as a header, checking to see if your request works that way.
3. Using the same manually constructed Authorization header, verify that it matches that produced by urllib3.

I don't see anything very wrong with what you're trying to do, so it may be that the Bitbucket API may not be acting as you expect. Try experimenting with cURL to see if you can get it to work there.

Finally, a quick skim of the PyUpdater code suggests that they're using a method called `_get_http_pool`, not `get_http_pool`, and that the latter is deprecated. That may be your issue here; if so, let me know so we can close this issue.

**Comment by sigmavirus24** [comment]
Hi there! Thanks for opening this issue. Unfortunately, it seems this is a request for help instead of a report of a defect in the project. Please use [StackOverflow](https://stackoverflow.com) for general usage questions instead and only report defects here. It seems that @haikuginger has set you on the right path. If you need further help, please use StackOverflow.
