### ISSUE TITLE
'ProxyManager' object has no attribute 'host'

### ISSUE THREAD

**Issue by rustyonrampage** [shazow/urllib3#1322]
I am testing the ProxyManager but it's giving the error. It is working fine if I directly call Request method of Proxymanager instead of passing it to Pool Manager. Even though the proxy server is inaccessible/ wrong, different exception needs to be thrown.

` import urllib3 

proxy = urllib3.ProxyManager('https://myproxy.com:8080/')

http = urllib3.PoolManager(_proxy=proxy)

r = http.request("Get",'https://google.com/')
`

![weired](https://user-images.githubusercontent.com/4447377/35580510-11266676-060b-11e8-9016-478e157f89ac.PNG)

**Comment by haikuginger** [comment]
@rustyonrampage, `ProxyManager` should not be passed to `PoolManager`, but should be instantiated itself and used in an identical manner to a `PoolManager`.

`ConnectionPool` does not expect to receive a `ProxyManager` in the `_proxy` keyword argument; it expects a parsed URL object, which is created and passed automatically when using the `ProxyManager` object directly.

Please note for the future that ideally, tracebacks should be presented as text, rather than as images.
