### ISSUE TITLE
Headers are always lower case, regardless of how they come on the wire.

### ISSUE THREAD

**Issue by Lukasa** [shazow/urllib3#236]
Initially shown by kennethreitz/requests#1561. Is this intended behaviour, or are you open to me changing that to maintain case?
##

**Comment by sigmavirus24** [comment]
Hm, I thought this was fixed recently.

**Comment by AdamWill** [comment]
I actually just ran into this with the test suite for https://github.com/gabrielfalcao/HTTPretty/ , which has a test that expects to find a header called 'Server' in a urllib3 response. It works with urllib3 1.19.1; it does *not* work (because the header name is changed to 'server') with urllib3 1.10.2 . I realize that's quite a wide range, but it's the delta I have right now :P

**Comment by Lukasa** [comment]
Cool, I'm calling this fixed then. 😁
