### ISSUE TITLE
Allow ssl certs/keys as buffer instead of file path

### ISSUE THREAD

**Issue by sholsapp** [shazow/urllib3#474]
I would like to be able to provide certificates and private keys as buffers instead of file paths to, e.g., `urllib3.util.ssl_wrap_socket`.

I think the reason this wasn't done before was because the `ssl`'s way of handling certificates and private keys was through file paths (see https://docs.python.org/2/library/ssl.html#ssl.SSLContext.wrap_socket). If `urllib3` is making a move to @alekstorm's `backports.ssl` package, then this is something that we can solve! If @shazow and @alekstorm are open to such a change, I don't mind diving in to this, because I have a handful of applications that aren't allowed to serialize their certificates and private keys to disk.

Would you both agree that using `backports.ssl` to solve this problem is correct? Would you like to see this change?

**Comment by hatRiot** [comment]
Archaic issue, and may already be outdated, but @sholsapp did you ever come up with a solution?  I need to load certs from a buffer, as opposed to a file path, and can't seem to trace through the related issues to see if a solution was ever reached.

**Comment by sholsapp** [comment]
Hey @hatRiot a solution was never reached.

**Comment by Lukasa** [comment]
A solution has been reached. As of urllib3 1.17 you can do this: 

```python
import certifi
import urllib3
import urllib3.contrib.pyopenssl

# This only works with PyOpenSSL. If you want it to work with the stdlib, you
# have to get the appropriate functionality in the stdlib, which doesn't allow
# loading certs/keys from memory.
urllib3.contrib.pyopenssl.inject_into_urllib3()

ctx = urllib3.util.ssl_.create_urllib3_context()
ctx.load_verify_locations(cafile=certifi.where())

# At this point, ctx._ctx is a PyOpenSSL Context object. If you have a PyOpenSSL
# X509 object and PKey object, you can then do this:
x509, pkey = get_my_credentials_somehow()
ctx._ctx.use_certificate(x509)
ctx._ctx.use_privatekey(pkey)

# You can now load a PoolManager and tell it to always use this SSLContext.
http = urllib3.PoolManager(ssl_context=ctx)

# Use the PoolManager as usual.
```

This is now the preferred way to get low-level control over your TLS config. Please note that we *always* encourage you to all `create_urllib3_context`, because that will always give you an object that is configured securely and will work with the currently urllib3 you're using. In your case, you'll want to assert that `isinstance(ctx, urllib3.contrib.pyopenssl.PyOpenSSLContext)` is true.

For this reason, I consider this issue addressed. I'm inclined to want to push more and more of this TLS configuration work into this kind of model.

/cc @tiran in case he wants to prod the stdlib to get a proper API for this, in which case I'll happily add that API to the PyOpenSSLContext object we have here.

**Comment by hatRiot** [comment]
[Looks](https://bugs.python.org/issue16487) like it's been a long time coming in stdlib.
