### ISSUE TITLE
Really don't spam InsecurePlatformWarning

### ISSUE THREAD

**Issue by tlynn** [shazow/urllib3#602]
urllib3 should configure its warnings using append=True to avoid overriding the user's preferences as specified with python -W or PYTHONWARNINGS.

If this issue were fixed, the user could work around pypa/pip#2681 with

    export PYTHONWARNINGS="ignore:A true SSLContext object is not available"

Additionally, the urllib3 docs are very unclear about why this is considered worth warning the end user about, particularly given that adding this strange message has effectively introduced a bug in hundreds of other projects.

**Comment by dstufft** [comment]
For what it's worth, the security concerns:

* On Python 2.6 urllib3 cannot set the allowed ciphers, making it possible that you'll connect using an insecure cipher using whatever the default is (most likely includes ``EXPORT`` ciphers).
* On Python <2.7.9 and 2.6 urllib3 cannot disable the use of SSLv2 or SSLv3 without pinning to explicitly TLSv1.0 (and it cannot pin to TLSv1.1 or TLSv1.2), making it possible that you'll connect using an insecure version of the SSL/TLS protocol.
* On Python <2.7.9 and 2.6 urllib3 cannot disable TLS Compression, making it possible for attackers to possibly determine the contents of an encrypted stream using the CRIME attack.
* On Python <2.7.9 and 2.6 urllib3 cannot set specific options, this is a big deal because it's caused requests to have to rollback the removal of the weak 1024 bit roots because it could not set the setting that instructs OpenSSL to prefer a shorter, trusted path over the entire path that the server provided.
* On Python <2.7.9 and 2.6 urllib3 cannot use SNI, this is less directly a security sensitive item, however the lack of SNI can cause people to disable ssl verification on sites that require SNI which means that missing SNI indirectly incentivizes people to downgrade their security.

**Comment by Lukasa** [comment]
> particularly given that adding this strange message has effectively introduced a bug in hundreds of other projects.

I'm sorry, but this sentiment is ridiculous. The correct sentiment is "this strange message has revealed a bug in hundreds of other projects".

Not having an `SSLContext` object exposes users to security risks without giving us any tools to mitigate them. Users have every right to know that the projects they use are not secure, and developers should be aware that it is within their power to secure their projects.

However, I do think the `append=True` approach is a reasonable one. The purpose of warnings is always that users should be able to turn them off, and generally speaking I'm ok with making that possible.

**Comment by tlynn** [comment]
Thanks for providing the list of security concerns (and for your efforts improving Python TLS support in general). Secure configuration doesn't seem impossible (on Python 2.7) under those constraints if you trust the server configuration, e.g. by specifying TLS and AES-GCM and downloading from PyPI, though I appreciate it's hard to assure security in a general public PKI setting.  I presume you can pin TLS 1.2 if you know the server supports it?  Re. requests, I'd have thought the 1024 bit roots could have been added only on weaker platforms, but I haven't seen the issue.

Anyway, I look forward to seeing append=True in a release.

**Comment by shazow** [comment]
> urllib3 should configure its warnings using append=True to avoid overriding the user's preferences as specified with python -W or PYTHONWARNINGS.

That sounds good.

> Additionally, the urllib3 docs are very unclear about why this is considered worth warning the end user about...

@dstufft Thanks for going over that! Would indeed be swell to include this in our security section of the docs, though I assume that even this list is not exhaustive.

@tlynn Would you like to make these changes? I'd be happy to merge. :)

**Comment by sigmavirus24** [comment]
> I assume that even this list is not exhaustive.

Correct. That's just a list of the larger problems that people *should* care about.

**Comment by Lukasa** [comment]
> Re. requests, I'd have thought the 1024 bit roots could have been added only on weaker platforms, but I haven't seen the issue.

Just in case anyone comes in here and wonders what we're talking about, see: kennethreitz/requests#2455, and certifi/python-certifi#20.

**Comment by devmanhinton** [comment]
Just want to leave this here as a helpful comment to others might stop by. Please let me know if any of the following is incorrect.

Errors from python < 2.7.9 etc.. are only concerning if said version is used to run the server. It does not actually affect the veracity of the certificate generated by `letsencrypt` 

For instance, we use python3 with nginx. Since nginx is not supported we are installing using the `certonly` `standalone` functionality in python2 (2.7.1 to be exact).

So most of this (and a few other related issues) revolve around whether `letsencrypt` has any responsibility to warn users about the security flaws in python < 2.7.9 (thanks to @dstufft for his synopsis of the issue).  

My 2cents is no. If you are running a server with older python it is on you to understand its security flaws.

**Comment by sigmavirus24** [comment]
@devmanhinton why aren't you providing this feedback to the letsencrypt team? Further, why are you talking about aspects of that project as if everyone on this issue is aware of them?

If something in letsencrypt is using urllib3 and urllib3 is generating those warnings, they're for a good reason. Most people who are using an older Python (regardless of the purpose of why they are running it) are grossly under-educated about the security flaws of those versions of Python. We're warning about exactly 1 of those flaws. Python 2.7.1, is susceptible to **numerous** CVEs and if its meant to be running a server for a service that is intended to be secure, you're allowing for a large number of attacks as it is. If that's your decision, use one of the numerous solutions documented to silence this if it is that irksome to you.
