### ISSUE TITLE
Fix AppEngine support

### ISSUE THREAD

**Issue by shazow** [shazow/urllib3#618]
We claim urllib3 works with AppEngine but looks like it's broken today (as of a few months ago). Nobody on our core team uses AppEngine, so maintaining support for it has been a substantial drain.

Ideally, we'd like official support/resources from the Google Cloud/AppEngine team to maintain support for AppEngine.

Related issues:
- https://github.com/shazow/urllib3/issues/583 (urlfetch is not used when it should be)
- https://github.com/kennethreitz/requests/issues/2595 (chunked-encoding streaming is broken)

**Comment by t-8ch** [comment]
Fun fact: The python appengine SDK even ships with requests/urllib3.

**Comment by t-8ch** [comment]
So the first problem with kennethreitz/requests#2595 is:

In `requests/models.py` we have:
```python
try:
      # Special case for urllib3.
      try:
          for chunk in self.raw.stream(chunk_size, decode_content=True):
              yield chunk
      except ProtocolError as e:
          raise ChunkedEncodingError(e)
      except DecodeError as e:
          raise ContentDecodingError(e)
      except ReadTimeoutError as e:
          raise ConnectionError(e)
except AttributeError as e:
      # Standard file-like object.
      while True:
          chunk = self.raw.read(chunk_size)
          if not chunk:
              break
          yield chunk

```

Deeper in the stack, in `urllib3/response.py:HTTPResponse.read_chunked` we
execute:

```py
self._original_response._method.upper() == 'HEAD'
```

On Appengine `httplib.HTTPResponse` is an `int` which does not have an `upper`
method. We get an `AttributeError` which bubbles up and makes requests fall back
to the nondecompressing branch.

So the error is with requests und urllib3.
Requests should do a better check than just waiting for `AttributeError`s and
urllib3 should not access private fields of other classes. (There was even a
FIXME)

But no mention of Appengine without it being broken: Even after fixing this we
run into a different chunked encoding exception. Fun!

**Comment by agfor** [comment]
@t-8ch I've been looking into it as well when I have time. I tracked down the second exception you mention. The problem is that the GAE httplib response object, stored as `_fp` on the response object, has already been un-chunked, despite GAE passing through the chunked header. So when urllib3 tries to determine the chunk length, it gets a line of the response rather than a line giving the chunk length.

It seems like a GAE bug, but one that urllib3 (or, alternatively, requests) should be able to work around.

**Comment by t-8ch** [comment]
@agfor Did you test it on the real appengine? It might only be the local urlfetch stub.
Could you test #620 on the real appengine?

**Comment by agfor** [comment]
@t-8ch I applied the patch and deployed it to GAE (after fixing the typo) and I'm still getting the `IncompleteReadError`.

**Comment by agfor** [comment]
A workaround for this if you don't need to use the GAE urlfetch api is to [switch the GAE httplib to use sockets](https://cloud.google.com/appengine/docs/python/sockets/#making_httplib_use_sockets) by adding this to `app.yaml`:

```
env_variables:
  GAE_USE_SOCKETS_HTTPLIB : 'anyvalue'
```

**Comment by shazow** [comment]
@agfor A very expensive workaround, for many. :/

**Comment by agfor** [comment]
@shazow Yeah. For now, I'm recommending people using the Braintree library stick with older versions of requests. If they need to upgrade they can apply this fix: https://github.com/agfor/requests/commit/6f7af88464504d6c9a4f84ce9c9535d2eb941b39 but the configuration change is so simple I thought it should be mentioned even if it doesn't work for a lot of people.

**Comment by t-8ch** [comment]
So urlfetch does not support chunked encoding and has limits on [request and response size (10M/32M)](https://cloud.google.com/appengine/docs/python/urlfetch/#Python_Quotas_and_limits).
And the socket stuff costs money...
I think if we want to do this properly we have to make people explicitly choose what they want to use.

**Comment by agfor** [comment]
@t-8ch Could you clarify why this worked before https://github.com/shazow/urllib3/commit/f21c2a2b73e4256ba2787f8470dbee6872987d2d if the problem is solely with GAE?

**Comment by t-8ch** [comment]
@agfor I assume the httplib replacement in appengine simply did not do chunked encoding.
We used to let httplib handle this for us, now we do it ourselves and AppEngine gives us wrong information about the data coming in.
So I think AppEngine is at fault, if they dechunk the response they have to remove the header telling us, the response is chunked.

**Comment by agfor** [comment]
Because of [this SO question](http://stackoverflow.com/questions/33037003/braintree-errors-with-gae-connection-errors-5-attempt-to-get-blocked-socket) I took another look at this.

With version `1.9.27.375` of the GAE Python SDK and either kennethreitz/requests@978a89d or that version of requests with shazow/urllib3@4197b68 dropped in, I get:

```
... snip ...
  File "/Users/agf/projects/appengine/braintree-python/requests/api.py", line 109, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/Users/agf/projects/appengine/braintree-python/requests/api.py", line 50, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/Users/agf/projects/appengine/braintree-python/requests/sessions.py", line 471, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/agf/projects/appengine/braintree-python/requests/sessions.py", line 579, in send
    r = adapter.send(request, **kwargs)
  File "/Users/agf/projects/appengine/braintree-python/requests/adapters.py", line 370, in send
    timeout=timeout
  File "/Users/agf/projects/appengine/braintree-python/requests/packages/urllib3/connectionpool.py", line 558, in urlopen
    body=body, headers=headers)
  File "/Users/agf/projects/appengine/braintree-python/requests/packages/urllib3/connectionpool.py", line 389, in _make_request
    assert_header_parsing(httplib_response.msg)
  File "/Users/agf/projects/appengine/braintree-python/requests/packages/urllib3/util/response.py", line 48, in assert_header_parsing
    type(headers)))
TypeError: expected httplib.Message, got <type 'instance'>.
```

when developing locally, and 


```
... snip ...
  File "/base/data/home/apps/s~braintree-python/1.387756493334177157/requests/api.py", line 109, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/base/data/home/apps/s~braintree-python/1.387756493334177157/requests/api.py", line 50, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/base/data/home/apps/s~braintree-python/1.387756493334177157/requests/sessions.py", line 471, in request
    resp = self.send(prep, **send_kwargs)
  File "/base/data/home/apps/s~braintree-python/1.387756493334177157/requests/sessions.py", line 611, in send
    r.content
  File "/base/data/home/apps/s~braintree-python/1.387756493334177157/requests/models.py", line 734, in content
    self._content = bytes().join(self.iter_content(CONTENT_CHUNK_SIZE)) or bytes()
  File "/base/data/home/apps/s~braintree-python/1.387756493334177157/requests/models.py", line 660, in generate
    raise ChunkedEncodingError(e)
ChunkedEncodingError: ('Connection broken: IncompleteRead(33 bytes read)', IncompleteRead(33 bytes read))
```

when deployed to GAE.

With the old, working version of requests / urllib3, things still work fine with the new version of the SDK.

**Comment by Lukasa** [comment]
@agfor What's the "old, working" version of requests/urllib3, specifically?

**Comment by agfor** [comment]
@Lukasa requests 2.6.0 and earlier / urllib3 before f21c2a2b73e4256ba2787f8470dbee6872987d2d (See https://github.com/kennethreitz/requests/issues/2595)

**Comment by Lukasa** [comment]
@agfor I *suspect* that what you actually need is the work merged as part of #664. However, requests does not consider GAE to be a supported platform, and is unlikely to enable support for this functionality. This is especially true as the change in #644 is at the `PoolManager` level, which requests does not use (we use `ConnectionPool`s directly).

You may want to investigate whether the functionality introduced in #664 works for you: if it does, it may be more effective for you to drop down a level and primarily use urllib3 if you intend to deploy on GAE.

**Comment by agfor** [comment]
If you're interested, agfor/requests@655dc08 is the diff required to get requests working with chunked encoding on AppEngine, with the second diff due to changes in urllib3 merged in since requests 2.7.0.

**Comment by snarfed** [comment]
oh man, that's exciting. nice work!

**Comment by juanAFernandez** [comment]
cool man!

**Comment by mikelambert** [comment]
Boo, I just ran into this today. @Lukasa , have you taken a peek at @agfor 's change? Is that something urllib3 would consider upstreaming? Or does the "GAE is not a supported platform" mean you would reject such a patch if upstreamed?

For anyone else working on this, where you think the changes would be easier to solve by making AppEngine's httplib/socket act more like python's built-in libraries, I believe you can do that by submitting patches upstream here:
https://github.com/GoogleCloudPlatform/appengine-python-vm-runtime/blob/master/python_vm_runtime/google/appengine/dist/
I understand the urllib3 folks do not have the bandwidth/time/responsibility to test AppEngine-unique behaviors (and/or accept technical hacks to urllib3 to support AppEngine), so didn't mean to imply that here. But frustrated others (such as @agfor , when he had time to hack on this, or others who come here in the future) may be more motivated to try to improve httplib directly.

Alternately (for those who come upon this thread, like myself, because of this breakage), you can make appengine use the builtin sockets/httplib library by adding this to app.yaml, which ensures they should work with urllib3:
env_variables:
  GAE_USE_SOCKETS_HTTPLIB : '1'

However, there are a few consequences of using raw sockets, as described on https://cloud.google.com/appengine/docs/python/sockets/ (most notably, you cannot access google.com domains, which means Google API libraries typically won't work.)
 
Also ssl (and consequently HTTPSConnection) are not included by default with AppEngine, unless you manually include the OpenSSL library in your app.yaml using the "libraries:" directive (described in the previous link, under OpenSSL). And relatedly, this should *not* be added if you're running on Appengine Managed VMs, as they include ssl by default and do not work with the "libraries:" directive.

Also of note I discovered while investigating, it appears appengine is including a 6-month-old requests 2.6 (which includes urllib3 0.10.2) instead of requests 2.8 (which includes urllib3 0.12). If anyone is interested or cares, I believe you can submit a pull request here to upgrade it:
https://github.com/GoogleCloudPlatform/appengine-python-vm-runtime/tree/master/python_vm_runtime/lib/requests/requests

**Comment by Lukasa** [comment]
@mikelambert To be clear, my understanding is that urllib3 considers GAE a "best effort" project. That is, we maintain code in-tree (with tests) that can in principle support GAE. It's Requests' that considers GAE unsupported, though even there we're aiming to have something in the requests-toolbelt that will help GAE work for requests (see sigmavirus24/requests-toolbelt#114).

**Comment by danmcclure** [comment]
Thank you @agfor !!!

**Comment by hamx0r** [comment]
@mikelambert another _consequence_ of using sockets is financial cost.  For those doing pet projects within the free tiers of Google Cloud services, using sockets makes it not-free.  I did, find, however that the socket solution worked!

Furthermore, it seems the `requests` module [you linked to](https://github.com/GoogleCloudPlatform/appengine-python-vm-runtime/tree/master/python_vm_runtime/lib/requests/requests) is for another Google project.  `requests` is not available as one of the [provided packages in GAE](https://cloud.google.com/appengine/docs/python/tools/libraries27), so I'd assume Google isn't maintaining their own variant.

When I first tried @agfor 's patch it didn't seem to work.  I may have had a messy workspace, because after deleting all requests files, then `pip install -t lib requests` installed requests 2.8.1, which worked fine after applying the patch.  If this is primarily a `requests` issue, perhaps there can be a branch off the 2.8.1 release which has this patch applied, and the branch could be named `GAE` until the `requests` main branch works with GAE again.  

Lastly, the GAE API has `urlfetch` which one could use instead of `requests`.  It's well documented and is known to work with GAE (and reasonably expected to keep working with GAE =)
https://cloud.google.com/appengine/docs/python/urlfetch/

**Comment by snarfed** [comment]
@hamx0r using sockets on app engine does require you to sign up for billing, but doesn't actually cost money. the signup requirement is basically just a heavyweight captcha. details: https://cloud.google.com/appengine/docs/quotas#Sockets , https://cloud.google.com/appengine/pricing

and you're right that the requests lib bundled in the sdk and managed vm isn't directly usable by apps. it's just used internally. details: https://groups.google.com/d/topic/google-appengine/xhnLnVbIvGY/discussion

**Comment by jonparrott** [comment]
@shazow is this issue satisfied by `contib.appengine`? It seems getting requests to work on app engine is a [separate issue](https://github.com/sigmavirus24/requests-toolbelt/pull/114).

**Comment by shazow** [comment]
@jonparrott You're right, closing! :)
