### ISSUE TITLE
Likely bug in retry/release-conn code, need tests

### ISSUE THREAD

**Issue by shazow** [shazow/urllib3#651]
In this change: https://github.com/shazow/urllib3/pull/647/files#diff-211abff6a07837e4a89a8663a89d2c84R582

@jlatherfold writes:

> For the (TimeoutError, HTTPException, SocketError, ConnectionError) exception handler you don't raise (presumably because there may be retries) and you will go on to release the conn and make another call to urlopen (if retries). But you call it with release_conn=True (since you've just set it to true) - what happens if that call succeeds? You'll release the conn back to the pool before the response is read. At least that's what it looks like to me.

**Comment by jlatherfold** [comment]
I will try and confirm this next week sometime, but writing a test to force it might not be so easy.

**Comment by shazow** [comment]
Take a look at the socketlevel tests in #647, should be some good examples.

**Comment by jlatherfold** [comment]
Hi,

I ran a few trial runs with your changes and set read timeout low enough to force the issue. I set retries=1 and got a lot of retries that succeeded so the problem that I thought would occur didn't - I couldn't confirm that this is an issue. You could probably be certain if you did something like this (ie. use a local varaible instead of release_conn):

put_conn_on_error = False
try:
    # make call...
except:
    conn = conn and conn.close()
    put_conn_on_error = True
finally:
    if release_conn or put_conn_on_error:
        self._put_conn(conn)
    
if retries:
    # try again...

Anyway, it seems ok as it is and I won't be doing any further tests on this for now.

**Comment by shazow** [comment]
Maybe, though not as certain as actually having a test in the suite which exercises this scenario. :) We'll see if we can add that later, thanks for trying!
