### ISSUE TITLE
TLS certificate verification ignores IP SANs

### ISSUE THREAD

**Issue by hashbrowncipher** [shazow/urllib3#759]
The current implementation of match_hostname ignores all SANs that are not DNS names.  In particular, it ignores IP address SANs.

Suggested fix: backport [match_hostname](https://hg.python.org/cpython/file/3.5/Lib/ssl.py#l254) from Python 3.5, which supports IP SANs.

**Comment by Lukasa** [comment]
Hi @hashbrowncipher.

Yeah, we've been aware of this for a while. It's a bit tricky because we also need to add support for pulling out the IP address fields when using PyOpenSSL. Additionally, it won't *always* work: older Pythons such as Python 2.6 can't guarantee that the IP address field will exist.

However, it's a good feature and one we should aim to have.

**Comment by hashbrowncipher** [comment]
When you mention "older Pythons such as Python 2.6 can't guarantee that the IP address field will exist", do you mean the ipaddress module?  Can we dep [ipaddress](https://pypi.python.org/pypi/ipaddress) from PyPI?

**Comment by Lukasa** [comment]
I do not. What I mean is that the ip address field in the SAN may not necessarily be present. Your concern is a real one as well, which also affects how we do this in urllib3 (can we safely vendor the ipaddress module?), but it may literally not work because some Python configurations may be unable to turn the X509 IP Address Name field in the SAN extension into something that `match_hostname` can see.

Again, still worth doing, but it makes this whole thing a bit subtle.

**Comment by theonewolf** [comment]
:+1: this feature would greatly help with intranets and enterprise environments, or even just home internal LANs that don't have DNS.  It is also an acceptable method of validating certificates that is currently ignored.

**Comment by tiran** [comment]
@Lukasa please don't follow the example of Python's stdlib. 

https://bugs.python.org/issue23239#msg244665
https://bugs.python.org/issue23239#msg262988

**Comment by Lukasa** [comment]
Closing in favour of #258.
