### ISSUE TITLE
RFE: Add Python 3.5 and PyPy3 to Travis

### ISSUE THREAD

**Issue by scop** [shazow/urllib3#768]
Would be useful to have Travis run tests against Python 3.5 and PyPy3 as well. I would have submitted a PR but simply adding py35 and pypy3 to .travis.yml and tox.ini didn't work out, it apparently requires something else.

**Comment by shazow** [comment]
+1, if anyone can figure out what would make travis happy.

**Comment by Lukasa** [comment]
That should be sufficient to make Travis happy.

**Comment by Lukasa** [comment]
Though Travis doesn't support PyPy3.

**Comment by scop** [comment]
Oh, sure it does, https://docs.travis-ci.com/user/languages/python#PyPy-Support

**Comment by Lukasa** [comment]
Huh, TIL. Well, in that case there's no special requirement for adding those two: that should be just fine.

**Comment by scop** [comment]
Ok, #770 has py35. Adding pypy3 seems to be trivial otherwise -- just add to .travis.yml and tox.ini -- but there are some test failures with it: https://travis-ci.org/scop/urllib3/jobs/98911025 (all of them due to the same issue apparently):

```
[...]
File "/home/travis/build/scop/urllib3/urllib3/util/ssl_.py", line 156, in assert_fingerprint
    cert_digest = hashfunc(cert).digest()
nose.proxy.TypeError: 'str' does not support the buffer interface
```

**Comment by Lukasa** [comment]
So this looks like a PyPy3 bug from my perspective. The type of the object returned by `sslsocket.getpeercert(binary_form=True)` is `bytes` on Python 3.2, and `str` on PyPy3. I don't think we should be defensive against this case, because `binary_form` clearly should return bytes and does on all other Python versions.

Let me file an upstream bug instead.

**Comment by Lukasa** [comment]
And indeed this was found last year by a urllib3 user, [as seen here](https://bitbucket.org/pypy/pypy/issues/1915/pypy3-ssl-getpeercert-binary_form-true-not). Unfortunately, the current release of PyPy 3 was released before that bug was fixed, and so we have no release of PyPy 3 containing that fix. We won't be able to add Travis support until such time as PyPy release a new version of PyPy 3 *and* Travis updates to use it, which will be quite a while.

**Comment by jayvdb** [comment]
Current state of play is Travis provides a PyPy3 5.2-alpha in a "as-is" unsupported fashion , but it requires `virtualenv` 15.0.2 which Travis doesnt install, and there is another problem wrt `tox` (https://github.com/travis-ci/travis-ci/issues/6304).

`tox-travis` v0.5 works around these problems (https://github.com/ryanhiebert/tox-travis/pull/24), but that was rejected with #938.

It is relatively easy to inline these fixes into `.travis.yml`, however we could also wait until PyPy3 5.2 is out of beta, and Travis properly supports it.

See also #936 .

**Comment by SethMichaelLarson** [comment]
Came here to ping this issue because of [travis-ci/travis-ci#6553](https://github.com/travis-ci/travis-ci/issues/6553) and whether or not we can now safely use PyPy 5.4?

**Comment by Lukasa** [comment]
This issue *is* closed.
