### ISSUE TITLE
Tests in contrib/ directory are never executed

### ISSUE THREAD

**Issue by strife25** [shazow/urllib3#854]
When running `make test` locally, tests in `test/contrib/` are never executed:

```
Name                      Stmts   Miss  Cover   Missing
-------------------------------------------------------
urllib3                      20      0   100%   
urllib3._collections        148      0   100%   
urllib3.connection          116      0   100%   
urllib3.connectionpool      235      0   100%   
urllib3.contrib               0      0   100%   
urllib3.contrib.socks        36      0   100%   
urllib3.exceptions           61      0   100%   
urllib3.fields               62      0   100%   
urllib3.filepost             32      0   100%   
urllib3.poolmanager         124      0   100%   
urllib3.request              33      0   100%   
urllib3.response            233      0   100%   
urllib3.util                  1      0   100%   
urllib3.util.connection      48      0   100%   
urllib3.util.request         20      0   100%   
urllib3.util.response        16      0   100%   
urllib3.util.retry           86      0   100%   
urllib3.util.ssl_            63      0   100%   
urllib3.util.timeout         48      0   100%   
urllib3.util.url             91      0   100%   
-------------------------------------------------------
TOTAL                      1473      0   100%   
----------------------------------------------------------------------
```

Example from one of the travis builds: https://travis-ci.org/shazow/urllib3/jobs/127431752#L246

**Comment by Lukasa** [comment]
Are you sure? That coverage output just indicates that there is no required coverage for the `contrib` module except for `socks`, which is currently deliberate: we do not collect coverage for the GAE or `pyopenssl` contrib modules because both are only situationally run.

I'm pretty confident that the tests *for* those modules do run, at least for `pyopenssl`, because I recently had to fix them and when I did I added them to the runs.

**Comment by haikuginger** [comment]
I can't speak for the maintainers, but based on the [current state](https://github.com/shazow/urllib3/blob/3239c172b19e41f41777db4bd55daae40c99b43d/.coveragerc) of the `.coveragerc` file, lack of required coverage seems intentional. Given that most of `contrib` is platform-dependent, that seems reasonable to me.

**Comment by strife25** [comment]
Ok, I will try playing around some more on my local machine - it's probably something I'm not seeing on my end and my basic tests to validate some changes weren't working. 

Thank you for the prompt response!

**Comment by strife25** [comment]
Found out my local issue, I wanted to specifically run contrib/pyopenssl.py tests and it was because i did not install the requirements defined in the `extras_require` for `secure`.

Running `pip install -e .[secure]` on my machine got it working.

**Comment by Lukasa** [comment]
\o/ Glad to hear it @strife25!
