### ISSUE TITLE
DNS Caching

### ISSUE THREAD

**Issue by alanhamlett** [shazow/urllib3#925]
Since urllib3 uses [socket.getaddrinfo](https://docs.python.org/3/library/socket.html#socket.getaddrinfo) to convert a host string into an IP address [1] does that mean we can cache DNS lookups somehow in urllib3?

[1] [urllib3/util/connection.py](https://github.com/shazow/urllib3/blob/e4e49128ac68e4b56e20482cd2bef1700ff30fd9/urllib3/util/connection.py#L75)

**Comment by Lukasa** [comment]
Generally speaking it's not worthwhile caching DNS lookups at the application layer. My suggestion is that, if you think DNS caching is worthwhile, it'd be better to use a local DNS resolver that can implement caching properly as specified by the relevant RFCs (e.g. nscd or dnsmasq).

Unless there is some disagreement from the other contributors, I think this is a bridge too far in terms of things we need to support. It's better to use a tool that is built for this job.

**Comment by alanhamlett** [comment]
My use case is a remote Python client running on user's machines where it doesn't make sense to run a local DNS resolver:

https://github.com/wakatime/wakatime

**Comment by Lukasa** [comment]
So, I'm sympathetic to that case, but again: if DNS lookups on a user's machine are slow I'm inclined to say that the user in question should take some action, rather than relying on the applications to implement a fully-fledged DNS cache. This is doubly true given that a large chunk of DNS information will be redundant, so if every application they have implements a DNS cache they'll be storing *quite a lot* of data more than once.

**Comment by alanhamlett** [comment]
OK thanks, closing the issue now.
