### ISSUE TITLE
It would be great to know the response sent by the server, when raising a ProxyError

### ISSUE THREAD

**Issue by nilleb** [shazow/urllib3#962]
When the proxy returns a 407 (authentication required)
It would be great to know the whole response
Because it could contain a lot of useful information
Like the supported authentication schemes, and the authentication realm

**Comment by Lukasa** [comment]
@nilleb I agree. However, right now httplib doesn't give us access to this information. That means that, unless we move away from httplib, we're not really able to provide that information.

**Comment by nilleb** [comment]
I think that, if we were allowed to change https://hg.python.org/cpython/file/3.5/Lib/http/client.py, line 831, with something else, that could help you, isn't it?

**Comment by haikuginger** [comment]
@nilleb, even if the httplib base code was changed to provide more information, we still likely wouldn't necessarily support that additional information for a while - one of urllib3's key goals is API compatibility back to Python 2.6, and such a feature would only be supported on whatever the latest version of Python would be at the time.

**Comment by nilleb** [comment]
Sorry for my naivety, but, to keep backwards compatibility, you could just
fill a 'response' property of your ProxyError if the caught OSError
contains such information.. that wouldn't break nothing, isn't it?

Le mar. 30 août 2016 à 15:53, Jesse Shapiro <notifications@github.com> a
écrit :

**Comment by haikuginger** [comment]
It likely wouldn't break anything _in and of itself_, but it would enable code that would likely break on older versions of Python. For example:

```python
try:
    resp = my_proxy.request('GET', 'http://google.com')
except ProxyError as e:
    log.warn('Proxy failed with message: {}'.format(e.response))
```

In a hypothetical Python 3.7 and a hypothetical urllib3 1.20 that has the feature you want, that works fine and is perfectly valid code. However, if someone were to run the code in Python 3.5, for example, it'd crash because the error wouldn't have the response property.

Obviously, there are ways to work around that, but it's an example of the kind of problem introducing platform-specific features can cause.

**Comment by sigmavirus24** [comment]
@haikuginger `e.response` could just be `None` on those versions. That said, I highly doubt the stdlib will accept a change that does this. @nilleb you absolutely should try though, and if and when that does merge, we should discuss this then. Until then, we're walking circles around hypotheticals.
